/**
 * Synthetic-media (AI video) detection.
 *
 * GoHeet is "REAL LIFE. REAL PEOPLE. REAL MOMENTS." — anything generated by an
 * AI model, rendered in 3D, or replayed from another screen is not allowed and
 * is taken down the moment it is detected.
 *
 * Two independent layers:
 *  1. Provenance — was this actually filmed live, in this app, in real time?
 *  2. Vision — does the frame itself look machine-generated?
 *
 * Both fail closed: if the check cannot run, the post is held for a human
 * instead of going public.
 */

export type SyntheticVerdict = {
  /** 0 = certainly a real camera moment, 100 = certainly machine-made. */
  score: number;
  reason: string;
  /** true when the post must be removed straight away. */
  synthetic: boolean;
};

/** Anything at or above this is taken down immediately. Deliberately strict. */
export const AI_REMOVE_THRESHOLD = 55;
/** Below removal but still suspicious: held for a human reviewer. */
export const AI_HOLD_THRESHOLD = 30;

const AI_RULES = `You are GoHeet's synthetic-media detector. GoHeet only allows moments filmed live
with the phone camera. Your single job is to judge how likely it is that this frame was NOT filmed
by a real camera pointing at the real world.

Score 100 for: AI/text-to-video or text-to-image output (Sora, Veo, Runway, Kling, Midjourney,
Stable Diffusion, etc.), deepfakes or face swaps, 3D renders, CGI, game footage, animation,
cartoons, avatars, digital art, illustrations, fully synthetic scenery.

Score 80-95 for: a screen recording or a photo of another screen (monitor, TV, phone, laptop),
re-filmed film/TV/streaming content, obvious re-uploads of produced media, heavy AI upscaling
or AI face filters that replace the face.

Score 60-80 for: strong AI artefacts — melted or extra fingers, warped text or signage, impossible
anatomy, inconsistent lighting or shadows, plastic-smooth waxy skin, over-perfect symmetry,
dreamlike backgrounds that dissolve, watermarks of generator tools.

Score 0-20 for: an ordinary handheld phone camera moment — real people, sensor noise, natural
motion blur, imperfect framing, everyday rooms, streets, food, pets, sport, selfies, nature.
Beauty filters, colour grading and app filters on a real camera frame are REAL: do not punish them.

Be strict but fair: never call a real, slightly blurry or dark phone photo AI.

Reply with JSON only: {"score": <0-100 integer>, "reason": "<max 20 words>"}`;

type Provenance = {
  /** Client reported the frames came from a live in-app camera track. */
  liveCapture: boolean;
  /** Hardware label of the camera track, e.g. "Back Dual Wide Camera". */
  cameraLabel: string | null;
  /** Length of the clip. */
  durationMs: number;
  /** How long the capture session had been open when the clip was published. */
  sessionElapsedMs: number;
  kind: "video" | "photo";
};

/**
 * Real-time proof: a clip can never be longer than the camera session that
 * produced it, and a video must come from a live camera track. This catches
 * pre-generated files pushed into the pipeline even when the frame itself
 * looks convincing.
 */
export function checkProvenance(p: Provenance): SyntheticVerdict | null {
  if (p.kind === "video" && !p.liveCapture) {
    return { score: 100, reason: "Clip was not filmed live in the GoHeet camera", synthetic: true };
  }
  if (p.durationMs > p.sessionElapsedMs + 15_000) {
    return { score: 100, reason: "Clip is longer than the live camera session", synthetic: true };
  }
  if (p.cameraLabel && /virtual|obs|manycam|droidcam|snap ?camera|epoccam|screen|capture card/i.test(p.cameraLabel)) {
    return { score: 100, reason: "A virtual camera was used instead of a real lens", synthetic: true };
  }
  return null;
}

/** Vision pass. Returns a hold-worthy verdict when the check cannot run. */
export async function detectSyntheticFrame(input: {
  imageUrl: string | null;
  caption: string;
}): Promise<SyntheticVerdict> {
  const apiKey = process.env["LOVABLE_API_KEY"];
  if (!apiKey || !input.imageUrl) {
    return { score: AI_HOLD_THRESHOLD, reason: "AI check unavailable", synthetic: false };
  }

  const content: Array<Record<string, unknown>> = [
    { type: "text", text: `Caption / on-screen text: ${input.caption || "(none)"}` },
    { type: "image_url", image_url: { url: input.imageUrl } },
  ];

  try {
    const res = await fetch("https://ai.gateway.lovable.dev/v1/chat/completions", {
      method: "POST",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({
        model: "google/gemini-3.8-flash",
        messages: [
          { role: "system", content: AI_RULES },
          { role: "user", content },
        ],
        response_format: { type: "json_object" },
      }),
    });
    if (!res.ok) {
      console.error("[ai-detect] gateway", res.status, await res.text());
      return { score: AI_HOLD_THRESHOLD, reason: "AI check unavailable", synthetic: false };
    }
    const json = (await res.json()) as { choices?: { message?: { content?: string } }[] };
    const raw = json.choices?.[0]?.message?.content ?? "";
    const parsed = JSON.parse(raw.replace(/^```json|```$/g, "").trim()) as { score?: number; reason?: string };
    const score = Math.max(0, Math.min(100, Math.round(Number(parsed.score ?? AI_HOLD_THRESHOLD))));
    return {
      score,
      reason: String(parsed.reason ?? "").slice(0, 200) || "Automatic AI check",
      synthetic: score >= AI_REMOVE_THRESHOLD,
    };
  } catch (err) {
    console.error("[ai-detect]", err);
    return { score: AI_HOLD_THRESHOLD, reason: "AI check failed", synthetic: false };
  }
}

export const AI_REJECTION_MESSAGE =
  "GoHeet is only for real moments filmed with your camera. This looked AI-generated, animated or re-filmed from a screen, so it was removed.";
