/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedBlockedRouteImport } from './routes/_authenticated/blocked'
import { Route as AuthenticatedCameraRouteImport } from './routes/_authenticated/camera'
import { Route as AuthenticatedDiscoverRouteImport } from './routes/_authenticated/discover'
import { Route as AuthenticatedEditProfileRouteImport } from './routes/_authenticated/edit-profile'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedMyCommentsRouteImport } from './routes/_authenticated/my-comments'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedSavedRouteImport } from './routes/_authenticated/saved'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedShareLaterRouteImport } from './routes/_authenticated/share-later'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedTrashRouteImport } from './routes/_authenticated/trash'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages.index'
import { Route as AuthenticatedMessagesConversationIdRouteImport } from './routes/_authenticated/messages.$conversationId'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedUUsernameIndexRouteImport } from './routes/_authenticated/u.$username.index'
import { Route as AuthenticatedUUsernameFollowersRouteImport } from './routes/_authenticated/u.$username.followers'
import { Route as AuthenticatedUUsernameFollowingRouteImport } from './routes/_authenticated/u.$username.following'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlockedRoute = AuthenticatedBlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCameraRoute = AuthenticatedCameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDiscoverRoute = AuthenticatedDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEditProfileRoute =
  AuthenticatedEditProfileRouteImport.update({
    id: '/edit-profile',
    path: '/edit-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyCommentsRoute = AuthenticatedMyCommentsRouteImport.update({
  id: '/my-comments',
  path: '/my-comments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSavedRoute = AuthenticatedSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShareLaterRoute = AuthenticatedShareLaterRouteImport.update({
  id: '/share-later',
  path: '/share-later',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrashRoute = AuthenticatedTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMessagesConversationIdRoute =
  AuthenticatedMessagesConversationIdRouteImport.update({
    id: '/messages/$conversationId',
    path: '/messages/$conversationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUUsernameIndexRoute =
  AuthenticatedUUsernameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedUUsernameRoute,
  } as any)
const AuthenticatedUUsernameFollowersRoute =
  AuthenticatedUUsernameFollowersRouteImport.update({
    id: '/followers',
    path: '/followers',
    getParentRoute: () => AuthenticatedUUsernameRoute,
  } as any)
const AuthenticatedUUsernameFollowingRoute =
  AuthenticatedUUsernameFollowingRouteImport.update({
    id: '/following',
    path: '/following',
    getParentRoute: () => AuthenticatedUUsernameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blocked': typeof AuthenticatedBlockedRoute
  '/camera': typeof AuthenticatedCameraRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/edit-profile': typeof AuthenticatedEditProfileRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/my-comments': typeof AuthenticatedMyCommentsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/share-later': typeof AuthenticatedShareLaterRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/legal/$doc': typeof LegalDocRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRouteWithChildren
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/u/$username/followers': typeof AuthenticatedUUsernameFollowersRoute
  '/u/$username/following': typeof AuthenticatedUUsernameFollowingRoute
  '/u/$username/': typeof AuthenticatedUUsernameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/blocked': typeof AuthenticatedBlockedRoute
  '/camera': typeof AuthenticatedCameraRoute
  '/discover': typeof AuthenticatedDiscoverRoute
  '/edit-profile': typeof AuthenticatedEditProfileRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/my-comments': typeof AuthenticatedMyCommentsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/saved': typeof AuthenticatedSavedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/share-later': typeof AuthenticatedShareLaterRoute
  '/support': typeof AuthenticatedSupportRoute
  '/trash': typeof AuthenticatedTrashRoute
  '/legal/$doc': typeof LegalDocRoute
  '/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/u/$username/followers': typeof AuthenticatedUUsernameFollowersRoute
  '/u/$username/following': typeof AuthenticatedUUsernameFollowingRoute
  '/u/$username': typeof AuthenticatedUUsernameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/blocked': typeof AuthenticatedBlockedRoute
  '/_authenticated/camera': typeof AuthenticatedCameraRoute
  '/_authenticated/discover': typeof AuthenticatedDiscoverRoute
  '/_authenticated/edit-profile': typeof AuthenticatedEditProfileRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/my-comments': typeof AuthenticatedMyCommentsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/saved': typeof AuthenticatedSavedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/share-later': typeof AuthenticatedShareLaterRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/trash': typeof AuthenticatedTrashRoute
  '/legal/$doc': typeof LegalDocRoute
  '/_authenticated/messages/$conversationId': typeof AuthenticatedMessagesConversationIdRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRouteWithChildren
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/u/$username/followers': typeof AuthenticatedUUsernameFollowersRoute
  '/_authenticated/u/$username/following': typeof AuthenticatedUUsernameFollowingRoute
  '/_authenticated/u/$username/': typeof AuthenticatedUUsernameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activity'
    | '/admin'
    | '/blocked'
    | '/camera'
    | '/discover'
    | '/edit-profile'
    | '/feed'
    | '/history'
    | '/my-comments'
    | '/onboarding'
    | '/saved'
    | '/settings'
    | '/share-later'
    | '/support'
    | '/trash'
    | '/legal/$doc'
    | '/messages/$conversationId'
    | '/u/$username'
    | '/messages/'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/u/$username/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/activity'
    | '/admin'
    | '/blocked'
    | '/camera'
    | '/discover'
    | '/edit-profile'
    | '/feed'
    | '/history'
    | '/my-comments'
    | '/onboarding'
    | '/saved'
    | '/settings'
    | '/share-later'
    | '/support'
    | '/trash'
    | '/legal/$doc'
    | '/messages/$conversationId'
    | '/messages'
    | '/u/$username/followers'
    | '/u/$username/following'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/activity'
    | '/_authenticated/admin'
    | '/_authenticated/blocked'
    | '/_authenticated/camera'
    | '/_authenticated/discover'
    | '/_authenticated/edit-profile'
    | '/_authenticated/feed'
    | '/_authenticated/history'
    | '/_authenticated/my-comments'
    | '/_authenticated/onboarding'
    | '/_authenticated/saved'
    | '/_authenticated/settings'
    | '/_authenticated/share-later'
    | '/_authenticated/support'
    | '/_authenticated/trash'
    | '/legal/$doc'
    | '/_authenticated/messages/$conversationId'
    | '/_authenticated/u/$username'
    | '/_authenticated/messages/'
    | '/_authenticated/u/$username/followers'
    | '/_authenticated/u/$username/following'
    | '/_authenticated/u/$username/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LegalDocRoute: typeof LegalDocRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blocked': {
      id: '/_authenticated/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof AuthenticatedBlockedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/camera': {
      id: '/_authenticated/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof AuthenticatedCameraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discover': {
      id: '/_authenticated/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AuthenticatedDiscoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/edit-profile': {
      id: '/_authenticated/edit-profile'
      path: '/edit-profile'
      fullPath: '/edit-profile'
      preLoaderRoute: typeof AuthenticatedEditProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-comments': {
      id: '/_authenticated/my-comments'
      path: '/my-comments'
      fullPath: '/my-comments'
      preLoaderRoute: typeof AuthenticatedMyCommentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/saved': {
      id: '/_authenticated/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof AuthenticatedSavedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/share-later': {
      id: '/_authenticated/share-later'
      path: '/share-later'
      fullPath: '/share-later'
      preLoaderRoute: typeof AuthenticatedShareLaterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trash': {
      id: '/_authenticated/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof AuthenticatedTrashRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages/$conversationId': {
      id: '/_authenticated/messages/$conversationId'
      path: '/messages/$conversationId'
      fullPath: '/messages/$conversationId'
      preLoaderRoute: typeof AuthenticatedMessagesConversationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/u/$username/': {
      id: '/_authenticated/u/$username/'
      path: '/'
      fullPath: '/u/$username/'
      preLoaderRoute: typeof AuthenticatedUUsernameIndexRouteImport
      parentRoute: typeof AuthenticatedUUsernameRoute
    }
    '/_authenticated/u/$username/followers': {
      id: '/_authenticated/u/$username/followers'
      path: '/followers'
      fullPath: '/u/$username/followers'
      preLoaderRoute: typeof AuthenticatedUUsernameFollowersRouteImport
      parentRoute: typeof AuthenticatedUUsernameRoute
    }
    '/_authenticated/u/$username/following': {
      id: '/_authenticated/u/$username/following'
      path: '/following'
      fullPath: '/u/$username/following'
      preLoaderRoute: typeof AuthenticatedUUsernameFollowingRouteImport
      parentRoute: typeof AuthenticatedUUsernameRoute
    }
  }
}

interface AuthenticatedUUsernameRouteChildren {
  AuthenticatedUUsernameFollowersRoute: typeof AuthenticatedUUsernameFollowersRoute
  AuthenticatedUUsernameFollowingRoute: typeof AuthenticatedUUsernameFollowingRoute
  AuthenticatedUUsernameIndexRoute: typeof AuthenticatedUUsernameIndexRoute
}

const AuthenticatedUUsernameRouteChildren: AuthenticatedUUsernameRouteChildren =
  {
    AuthenticatedUUsernameFollowersRoute: AuthenticatedUUsernameFollowersRoute,
    AuthenticatedUUsernameFollowingRoute: AuthenticatedUUsernameFollowingRoute,
    AuthenticatedUUsernameIndexRoute: AuthenticatedUUsernameIndexRoute,
  }

const AuthenticatedUUsernameRouteWithChildren =
  AuthenticatedUUsernameRoute._addFileChildren(
    AuthenticatedUUsernameRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedBlockedRoute: typeof AuthenticatedBlockedRoute
  AuthenticatedCameraRoute: typeof AuthenticatedCameraRoute
  AuthenticatedDiscoverRoute: typeof AuthenticatedDiscoverRoute
  AuthenticatedEditProfileRoute: typeof AuthenticatedEditProfileRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedMyCommentsRoute: typeof AuthenticatedMyCommentsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedSavedRoute: typeof AuthenticatedSavedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedShareLaterRoute: typeof AuthenticatedShareLaterRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTrashRoute: typeof AuthenticatedTrashRoute
  AuthenticatedMessagesConversationIdRoute: typeof AuthenticatedMessagesConversationIdRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRouteWithChildren
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedBlockedRoute: AuthenticatedBlockedRoute,
  AuthenticatedCameraRoute: AuthenticatedCameraRoute,
  AuthenticatedDiscoverRoute: AuthenticatedDiscoverRoute,
  AuthenticatedEditProfileRoute: AuthenticatedEditProfileRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedMyCommentsRoute: AuthenticatedMyCommentsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedSavedRoute: AuthenticatedSavedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedShareLaterRoute: AuthenticatedShareLaterRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTrashRoute: AuthenticatedTrashRoute,
  AuthenticatedMessagesConversationIdRoute:
    AuthenticatedMessagesConversationIdRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRouteWithChildren,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LegalDocRoute: LegalDocRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
